Add Azure Pipeline for SonarCloud
sonarsource-cfamily-examples/macos-cmake-azure-sc pull request #1
Opened 2021-06-17 14:20 UTC by tomasz-kaminski-sonarsource

2021-06-17 14:27 UTC, arseniy-sonar requested changes
Looks good, just the stray branch in the build-status badge

2021-06-17 14:27 UTC, arseniy-sonar commented on README.adoc
> +:img-build-status: https://dev.azure.com/sc-sq-c-family-examples/macos-cmake-azure-sc/_apis/build/status/sc-sq-c-family-examples.macos-cmake-azure-sc?branchName=azure-sc-analysis
```suggestion
:img-build-status: https://dev.azure.com/sc-sq-c-family-examples/macos-cmake-azure-sc/_apis/build/status/sc-sq-c-family-examples.macos-cmake-azure-sc
```

2021-06-17 14:27 UTC, arseniy-sonar commented on README.adoc
> +:uri-build-status: https://dev.azure.com/sc-sq-c-family-examples/macos-cmake-azure-sc/_build/latest?definitionId=2&branchName=azure-sc-analysis
```suggestion
:uri-build-status: https://dev.azure.com/sc-sq-c-family-examples/macos-cmake-azure-sc/_build/latest?definitionId=2
```

2021-06-18 07:04 UTC, tomasz-kaminski-sonarsource commented on README.adoc
> +:img-build-status: https://dev.azure.com/sc-sq-c-family-examples/macos-cmake-azure-sc/_apis/build/status/sc-sq-c-family-examples.macos-cmake-azure-sc?branchName=azure-sc-analysis
Removed all default branches

2021-06-18 08:44 UTC, merged